services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
    ports:
      - "8088:8080"
  app:
    container_name: ditto-app
    ports:
      - "8080:8081"
    build:
      dockerfile: Dockerfile
    restart: always