services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
    ports:
      - "8088:8080"
#  app:
#    container_name: batch-app
#    ports:
#      - "8086:8086"
#    build:
#      dockerfile: Dockerfile
#    restart: always