services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
    ports:
      - "8088:8080"

  activity:
    container_name: activity
    build:
      context: ./ditto-module-activity
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  gateway:
    container_name: gateway
    build:
      context: ./ditto-module-gateway
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  newsfeed:
    container_name: newsfeed
    build:
      context: ./ditto-module-newsfeed
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  stock:
    container_name: stock
    build:
      context: ./ditto-module-stock
      dockerfile: Dockerfile
    ports:
      - "8091:8091"

  user:
    container_name: user
    build:
      context: ./ditto-module-user
      dockerfile: Dockerfile
    ports:
      - "8087:8087"

