server:
  port: 8083
spring:
  main:
    web-application-type: reactive
  docker:
    compose:
      lifecycle-management: start_and_stop
      start:
        command: up
      stop:
        command: down
        timeout: 1m
  config:
    import:
      database.properties
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
    auth-code-expiration-millis: 1800000
#  redis:
#    pool:
#      min-idle: 0
#      max-idle: 8
#      max-active: 8
#  data:
#    redis:
#      port: 6379
#      host: localhost
#    port: 6379
#    host: localhost

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expire-length: ${JWT_EXPIRE_LENGTH}
